### ISSUE TITLE
dbt deps

### ISSUE THREAD

**Issue by misteliy** [calogica/dbt-expectations#10] opened 2020-11-07 10:35 UTC
with packages.yaml:

packages:
  - git: "https://github.com/calogica/dbt-expectations.git"
    revision: 0.1

running dbt deps I get this error:
Running with dbt=0.18.0
Encountered an error:
Got a non-zero returncode running: ['git', 'clone', '--depth', '1', 'git@github.com:calogica/dbt-date.git', '36b63a0bdea5f3e5d232c299b76e1160']

also having the dependencies in there directly does not solve the issue...

packages:
  - git: "https://github.com/calogica/dbt-date.git"
    revision: 0.2.1
  - git: "https://github.com/calogica/dbt-expectations.git"
    revision: 0.1

However...only having:

packages:
  - git: "https://github.com/calogica/dbt-date.git"
    revision: 0.2.1

results in dbt deps:
Running with dbt=0.18.0
Installing https://github.com/calogica/dbt-date.git@0.2.1
  Installed from revision 0.2.1

Installing fishtown-analytics/dbt_utils@0.6.2
  Installed from version 0.6.2

**Comment by clausherther** [comment] 2020-11-09 19:59
I'm so far not able to reproduce this using dbt 0.18.1, but I'll look into more. Thanks!

**Comment by misteliy** [comment] 2020-11-09 21:08
Unfortunately, also updating to 0.18.1 did not solve the issue:

dbt deps

Running with dbt=0.18.1
Encountered an error:
Got a non-zero returncode running: ['git', 'clone', '--depth', '1', 'git@github.com:calogica/dbt-expectations.git', '302c8ef7290af78b223a10403d76f27f']

**Comment by clausherther** [comment] 2020-11-09 21:53
Would you mind checking if you can perform a regular git clone of the repo somewhere on that same machine? I want to see if this a git access/permissions thing, or something about the packages.yml syntax.
```
git clone git@github.com:calogica/dbt-expectations.git
```

**Comment by clausherther** [comment] 2020-11-09 22:02
@misteliy also, would you mind replacing the ref in your `packages.yml` with 
```
packages:
  - git: "git@github.com:calogica/dbt-expectations.git"
    revision: 0.1
```

**Comment by clausherther** [comment] 2020-11-09 22:20
Actualy, nevermind, figured out the issue (needed to replace my refs to dbt-date with the https versions). I'll cut a new release you can use. In the meantime, you can test to see if it works for you by pulling against the `main` branch
```
packages:
  - git: "https://github.com/calogica/dbt-expectations.git"
    revision: main
```

**Comment by clausherther** [comment] 2020-11-09 22:23
Released as `revision: 0.1.2`

**Comment by clausherther** [comment] 2020-11-10 14:34
Closing as this was fixed in https://github.com/calogica/dbt-expectations/releases/tag/0.1.2 

Feel free to reopen if you're still having issues.

**Closed by clausherther** 2020-11-10 14:34 UTC

**Comment by samsheertc** [comment] 2022-01-06 04:56
I am having same issue


packages:
  - git: "https://gitlab.com/hcl55/dbt_music_data.git"
    revision: master

Here is the error

Got a non-zero returncode running: ['/usr/bin/git', 'clone', '--depth', '1', 'https://gitlab.com/hcl55/dbt_music_data.git', 'e9372429751ad90a6b7f28a298d50ac4'] Code: 10001

**Comment by clausherther** [comment] 2022-01-06 05:03
@samsheertc that's not this package, you're going to have to open an issue where the `dbt_music_data` repo is.
