### ISSUE TITLE
[BUG] expect_row_values_to_have_recent_data with dbt utils 1.0.0

### ISSUE THREAD

**Issue by olivierdet** [calogica/dbt-expectations#230] opened 2022-12-20 10:09 UTC
### Is this a new bug in dbt-expectations?

- [X] I believe this is a new bug in dbt-expectations
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior
`expect_row_values_to_have_recent_data` is failing with the following error 
`'dbt_utils' is undefined`
This happen when we migrate to elementary_data 0.6.6

### Expected Behavior
The test should not fail
### Steps To Reproduce
Install dbt utils 1.0.0 or 0.9.6
dbt_exepctation 0.8.0
elementary-data 0.6.6
### Environment

```markdown
- OS:linux
- Python:3.9
- dbt:1.3.1
- dbt-expectations:0.8.0
```

### Which database adapter are you using with dbt?

Note: dbt-expectations currently does not support database adapters are than the ones listed below.

- [ ] Postgres
- [X] Snowflake
- [ ] BigQuery

**Comment by clausherther** [comment] 2022-12-20 15:23
Hi @olivierdet, as of `dbt-expectations` release `0.8.0`, we no longer have a dependency on `dbt-utils`. Make sure you run `dbt clean && dbt deps` to remove old versions and download the 0.8.0 release.
Have you checked with elementary_data if this is caused by something on their end?
It would also help if you provided more of the error log, and also the contents of your `packages.yml` file.

**Comment by olivierdet** [comment] 2022-12-27 16:48
Hello, 
Yes, I've run the `clean and deps`. 
Here you'll find my package 
```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - package: tnightengale/dbt_meta_testing
    version: 0.3.6
  - package: Snowflake-Labs/dbt_constraints
    version: [">=0.5.0", "<0.6.0"]
  - package: calogica/dbt_expectations
    version: 0.8.0
  - package: elementary-data/elementary
    version: 0.6.6
```

Here the log message : 
```
[0m16:45:18.883710 [debug] [MainThread]: Flushing usage events
[0m16:45:19.443596 [error] [MainThread]: Encountered an error:
Compilation Error in test dbt_expectations_expect_row_values_to_have_recent_data_fact_admin_site_event_tracking_event_at__day__1___event_at_modules_datetime_date_today_modules_datetime_timedelta_14_ (models/lakehouse/core/fact_admin_site_event_tracking.yml)
  'dbt_utils' is undefined
  
  > in macro default__test_expect_row_values_to_have_recent_data (macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql)
  > called by macro test_expect_row_values_to_have_recent_data (macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql)
  > called by macro type_timestamp (macros/utils/data_types/data_type.sql)
  > called by test dbt_expectations_expect_row_values_to_have_recent_data_fact_admin_site_event_tracking_event_at__day__1___event_at_modules_datetime_date_today_modules_datetime_timedelta_14_ (models/lakehouse/core/fact_admin_site_event_tracking.yml)

```

I will also check with elementary package. I see that there are also contributor for this package.

**Comment by clausherther** [comment] 2022-12-27 17:07
Looks like this error comes from the inclusion of the `elementary` package then. We no longer use dbt_utils at all. It's possible they've overridden the `expect_row_values_to_have_recent_data` test and are still using dbt_utils in their version.

**Comment by Maayan-s** [comment] 2022-12-27 17:10
Hi @clausherther and @olivierdet, looking into it now. 
Will report my findings shortly.

**Comment by Maayan-s** [comment] 2022-12-27 17:58
Hi, 
We were able to recreate and understand why it happens. 
To support both dbt 1.0-1.2 and 1.3 and above, we created our own macros that call dbt if version>1.3 and dbt_utils if version<1.3.
One of these macros is named `type_timestamp`, which uses `dbt_utils`. 

We import `dbt_utils`, so I don't fully understand why it is undefined, but it sure happens although everything is installed properly:
![image](https://user-images.githubusercontent.com/22072028/209704549-2eb3a825-a4cd-45da-9b39-8a945da4eede.png)

 Anyway, we are thinking of a temp workaround for you @olivierdet, and will figure out the best solution for this. Also trying to understand if this is a bug in how dbt searches macros in packages, so we could report to them if needed.

**Comment by clausherther** [comment] 2022-12-27 19:38
@Maayan-s thanks for digging into this! I removed dependencies on dbt-utils b/c managing the chained relationship between dbt-date, dbt-utils and dbt-expectations got too much. Once dbt-core contained all the necessary date macros, I was able to remove dbt-utils from dbt-date and downstream. For `type_timestamp` we actually have a local version in `dbt-expectations` b/c the dbt-core version returns an imprecise value, I filed an [issue](https://github.com/dbt-labs/dbt-core/issues/6453) on dbt-core for that.

I don't super understand how the dbt elementary-data package works. How come this issue surfaces in a dbt-expectations macro?

**Comment by elongl** [comment] 2022-12-28 09:55
Hi @olivierdet @clausherther @Maayan-s, I'll try to elaborate on why we believe that happens.
The way dbt works is that upon compiling, it iterates over all the macros in the project.
That includes macros of packages as well.

dbt will work out the dependencies of each package and compile the dependencies first until it compiled all the macros throughout the project. For instance, for a user that uses `elementary`, it'll first compile `dbt-utils` which is a dependency package, and only then `elementary` itself.

For a user that installs both `dbt-expectations` and `elementary` as @olivierdet,
and given that `dbt-expectations`'s macros don't currently use package-scoping for the macro lookups (using `type_timestamp()` rather than `dbt.type_timestamp()`.
<img width="737" alt="image" src="https://user-images.githubusercontent.com/30181361/209791452-4c71d7bf-7194-4e10-bb5a-f2783e544f9e.png">

It could happen that `type_timestamp()` will resolve to `elementary.type_timestamp()` which in return will do the following lookup `{% set macro = dbt.type_timestamp or dbt_utils.type_timestamp %}` as @Maayan-s explained.

The problem here is that `dbt_utils`'s macros were not yet loaded (compiled) into the context object and therefore caused a crash when trying to access it.

We were able to fix it by [immediately returning the macros](https://github.com/elementary-data/dbt-data-reliability/pull/205) that we override and are likely to appear on other packages, we're releasing a hotfix now.

Hopefully that's clearer.

**Comment by Maayan-s** [comment] 2022-12-28 09:58
Got it, thanks for explaining. Yes, the dependencies are an issue for us as well.
The elementary package is no different than any other in how it works, this is why I do think that there is a bug in how dbt handles collisions in macro names. 
dbt-core, dbt-utils, elementary and dbt-expectations all have a macro named `type_timestamp`, and for some reason on a test from dbt-expectations it chooses to use the elementary macro. On the macro itself, the dbt-utils macro is referenced and is not found although it is installed. 

When I changed locally the code of dbt-expectations to explicit macro refs (`type_timestamp` -> `dbt_expectations.type_timestamp`) it fixed the issue. 
Would be happy to open a PR and change it here as well :) 

Anyway, we are changing the names of our macros to prevent this from our side as well.

**Comment by Maayan-s** [comment] 2022-12-28 10:03
@clausherther 
Changing locally the code of dbt-expectations to explicit macro refs (`type_timestamp()` -> `dbt_expectations.type_timestamp()`) will prevent this from happening with other packages in the future. 
Happy to open a PR if thats ok with you.

**Comment by clausherther** [comment] 2022-12-28 15:17
Ah, good to know, thanks both @Maayan-s and @elongl!
I'll change our references to be explicit, should probably do that for the dbt-core macros then as well? i.e. `dbt.type_int()` to be safe?

**Comment by elongl** [comment] 2022-12-28 15:27
Yes, that's is generally the recommended practice 👌🏽 
Thanks for your help! Much appreciated.

**Comment by clausherther** [comment] 2022-12-28 15:45
Ok, merged the PR and released as part of `0.8.1`, which should hopefully be on dbt package hub with the next hour or so. Thanks for everyone's help in tracking this down! 👍

**Comment by olivierdet** [comment] 2022-12-30 15:10
Hello, I try to install the dbt_expectation 0.8.2, but I’ve got exactly the same issue :-(

```
Compilation Error in test dbt_expectations_expect_row_values_to_have_recent_data_fact_admin_site_event_tracking_event_at__day__1___event_at_modules_datetime_date_today_modules_datetime_timedelta_14_ (models/lakehouse/core/fact_admin_site_event_tracking.yml)
  'dbt_utils' is undefined

  > in macro now (macros/calendar_date/now.sql)
  > called by macro default__test_expect_row_values_to_have_recent_data (macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql)
  > called by macro test_expect_row_values_to_have_recent_data (macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql)
  > called by macro current_timestamp (macros/utils/cross_db_utils/current_timestamp.sql)
  > called by test dbt_expectations_expect_row_values_to_have_recent_data_fact_admin_site_event_tracking_event_at__day__1___event_at_modules_datetime_date_today_modules_datetime_timedelta_14_ (models/lakehouse/core/fact_admin_site_event_tracking.yml)
```

**Comment by gary-beautypie** [comment] 2022-12-30 21:28
Same issue here, looks as though the `current_timestamp()` [here](https://github.com/calogica/dbt-date/blob/main/macros/calendar_date/now.sql) is getting resolved as an expected macro from dbt-utils or something? As it was [pre-1.0.0](https://github.com/dbt-labs/dbt-utils/blob/0.9.latest/macros/cross_db_utils/current_timestamp.sql)

**Comment by clausherther** [comment] 2022-12-30 21:43
@gary-beautypie ugh, I missed that in dbt-date yesterday, thanks for catching that. To be clear, this is only an issue if used in conjunction with dbt-utils. I'll merge your PR later today and release a patch on dbt-date.

**Comment by clausherther** [comment] 2022-12-30 21:57
Ok, I released both updates that address the `dbt.*` issues in dbt-date in 0.7.2, which should be on dbt package hub in the next hour or so. The current release of dbt-expectations (0.8.2) should just pull that in once available. Thanks everyone! 
(Leaving this open for now.)

**Comment by gary-beautypie** [comment] 2022-12-30 22:26
dbt-date 0.7.2 seems so have resolved this for me 👌 thanks!

**Closed** 2022-12-31 01:33 UTC
